<?php
$not_found = '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15.5,12C18,12 20,14 20,16.5C20,17.38 19.75,18.21 19.31,18.9L22.39,22L21,23.39L17.88,20.32C17.19,20.75 16.37,21 15.5,21C13,21 11,19 11,16.5C11,14 13,12 15.5,12M15.5,14A2.5,2.5 0 0,0 13,16.5A2.5,2.5 0 0,0 15.5,19A2.5,2.5 0 0,0 18,16.5A2.5,2.5 0 0,0 15.5,14M7,15V17H9C9.14,18.55 9.8,19.94 10.81,21H5C3.89,21 3,20.1 3,19V5C3,3.89 3.89,3 5,3H19A2,2 0 0,1 21,5V13.03C19.85,11.21 17.82,10 15.5,10C14.23,10 13.04,10.37 12.04,11H7V13H10C9.64,13.6 9.34,14.28 9.17,15H7M17,9V7H7V9H17Z" /></svg> ' . $wo["lang"]["no_result"] . '</div>';
$type_to_find = '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M9.62,12L12,5.67L14.37,12M11,3L5.5,17H7.75L8.87,14H15.12L16.25,17H18.5L13,3H11Z" /></svg> ' . $wo["lang"]["what_are_looking_for"] . '</div>';
?>
<style>
    body {
        padding-right: 0 !important;
    }
    @media (min-width: 992px) {
        .content-container {
            width: 97vw !important;
        }
    }
</style>
<div class="page-margin">

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBjqfSGNT7sHqdAZ46ztbFWJgVQHitMP_Y&callback=initMap"
            type="text/javascript"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <div class="wow_main_float_head searchs">
        <div class="container-fluid">
 <!--            <form action="<?php echo Wo_SeoLink('index.php?link1=explore') ?>" method="get" class="search-filter-form" id="search_form">
                <center>
                    <div class="wow_search_head" style="width: 90%; margin: 10px 20px;">
                        <div class="wow_srch_fields">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.44,13.73L14.71,14H15.5L20.5,19L19,20.5L14,15.5V14.71L13.73,14.44C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3M9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5Z" /></svg>
                            <input type="text" name="query" id="query" placeholder="<?php echo $wo['lang']['keyword'];?>" value="<?php echo (isset($_GET['query'])) ? Wo_Secure($_GET['query']): '';?>" autocomplete="off">
                        </div>
                        <div class="wow_srch_fields">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" /></svg>
                            <select name="country" id="country">
                                <option value="all" selected><?php echo $wo['lang']['all'];?></option>
                                <?php
                                foreach ($wo['countries_name'] as $country_ids => $country) {
                                    $selected_c = (!empty($_GET['country']) && $_GET['country'] == $country_ids) ? ' selected': '';
                                    ?>
                                    <option value="<?php echo $country_ids;?>" <?php echo $selected_c?>><?php echo $country;?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="wow_srch_fields">
                            <div class="dropdown">
                                <button id="srch_fltrs" class="btn" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M6,13H18V11H6M3,6V8H21V6M10,18H14V16H10V18Z" /></svg> <?php echo $wo['lang']['filter'];?> <span class="caret"></span></button>
                                <ul class="dropdown-menu wow_srch_drp_mnu" aria-labelledby="srch_fltrs">
                                    <li>
                                        <div class="wow_form_fields">
                                            <label for="page_category">Category</label>
                                            <select class="form-control" name="page_category" id="page_category" onchange="GetPageSubCategory(this)">
                                                <option value="">All</option>
                                                <?php foreach ($wo['page_categories'] as $category_id => $category_name) {?>
                                                    <option value="<?php echo $category_id?>"><?php echo $category_name; ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="wow_form_fields">
                                            <label for="page_sub_category">Sub Category</label>
                                            <select name="page_sub_category" id="page_sub_category">
                                                <option value="">All</option>
                                                <?php
                                                if (!empty($wo['page_sub_categories'][array_keys($wo['page_categories'])[0]])) {
                                                    foreach ($wo['page_sub_categories'][array_keys($wo['page_categories'])[0]] as $id => $sub_category) { ?>
                                                        <option value="<?php echo $sub_category['id']?>"><?php echo $sub_category['lang']; ?></option>
                                                    <?php } } ?>
                                            </select>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="wow_srch_fields">
                            <button type="submit" class="btn btn-main btn-mat"><?php echo $wo['lang']['search'];?></button>
                        </div>
                    </div>
                </center>
            </form> -->
            <ul class="nav nav-tabs wow_srch_tabs">
                <!-- <li class="active">
                    <a data-toggle="tab" data-target="#users" href="#" class="btn btn-mat">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z" /></svg> <?php echo $wo['lang']['users'];?>
                    </a>
                </li> -->

            </ul>
            <?php
            $whereFilter = "";
            if (isset($_GET) && $_GET !="" && count($_GET) > 0) {
                if (isset($_GET['query']) && trim($_GET['query']) !="") {
                    $whereFilter .= " AND (page_name like ('%".addslashes($_GET['query'])."%') OR page_title like ('%".addslashes($_GET['query'])."%') ) ";
                }
                if (isset($_GET['country']) && trim($_GET['country']) !="" && $_GET['country'] !="all" && $_GET['country'] !=0) {
                    $whereFilter .= " AND countries = '".$_GET['country']."' ";
                }
                if (isset($_GET['page_category']) && trim($_GET['page_category']) !="") {
                    $whereFilter .= " AND page_category = '".$_GET['page_category']."' ";
                }
                if (isset($_GET['page_sub_category']) && trim($_GET['page_sub_category']) !="") {
                    $whereFilter .= " AND sub_category = '".$_GET['page_sub_category']."' ";
                }
            }
            require ('config.php');
            $whereFilter .=" limit 100";
            $con=mysqli_connect($sql_db_host,$sql_db_user,$sql_db_pass,$sql_db_name);
            $query = mysqli_query($con,"SELECT * FROM Wo_Users".$whereFilter);
            $data=array();
            while ($item = mysqli_fetch_array($query))
            {
                if($item['lat'] != "" && $item['lng'] != ""){
                    $VisURL = $wo['site_url'].'/'.$item['username'];
                    $imgURL = $wo['site_url'].'/'.$item['avatar'];
                    //$data['title']=$item['page_name'];
                    $data[]= array(
                        'title' => $item['username'],
                        'lat' => $item['lat'],
                        'lng' => $item['lng'],
                        'icon' => $imgURL,
                        'description' => '<div class="info_content" style ="text-align:center;padding:7px"><p>'.$item['username'].'</p>
                        <img src= '.$imgURL.' style ="width:40px; height: 40px;border-radius: 50%;"></br></br>
                        <a title="Open Page" target="_blank" style="text-decoration: none; border:1px solid green; padding:5px; border-radius:10px;" href='.$VisURL.'>'.$item['username'].'</a>
                        </div>'
                    );
                }
            }
            // if(empty($empty_array)){
            //     $data=$wo['rendom_user'];
            // }

            ?>
            <div class="row">
                <center>
                    <div class="col-12" style="width: 98%; margin: 10px; position: relative;">
                        <?php
                        if (isset($data) && count($data)>0) {
                            $okVar = 1;
                        }else{
                            ?>
                            <div class="alert alert-info">
                                <h4>No Result found!</h4>
                            </div>
                            <?php
                        }
                        ?>
                        <?php if ($wo['config']['pages'] == 1) { ?>

                            <script type="text/javascript">

                                var markers = <?php echo json_encode($data) ?>;
                                window.onload = function () {
                                    LoadMap();
                                }
                                function LoadMap() {
                                    var mapOptions = {
                                        center: new google.maps.LatLng(markers[0].lat, markers[0].lng),
                                        zoom: 4,
                                        mapTypeId: google.maps.MapTypeId.ROADMAP,
                                        fullscreenControl: true
                                    };
                                    var map = new google.maps.Map(document.getElementById("dvMap"), mapOptions);

                                    //Create and open InfoWindow.
                                    var infoWindow = new google.maps.InfoWindow();
                                        
                                    for (var i = 0; i < markers.length; i++) {
                                    var iconBase = '<?php echo $wo['config']['theme_url']."/img/blue-x.png";?>'; // Please add the absolute path  of the image folder
                                        var data = markers[i];
                                        var myLatlng = new google.maps.LatLng(data.lat, data.lng);
                                        var marker = new google.maps.Marker({
                                            position: myLatlng,
                                            map: map,
                                        //   icon: {
                                        //       url: iconBase,
                                        //       size: new google.maps.Size(36, 46),
                                        //       scaledSize: new google.maps.Size(36, 46),
                                        //       anchor: new google.maps.Point(0, 50),
                                        //     },
                                            //code for profile picture
                                            icon: {
                                                url: data.icon,
                                                size: new google.maps.Size(36, 46),
                                                scaledSize: new google.maps.Size(36, 46),
                                                anchor: new google.maps.Point(0, 50),
                                            },
                                            title: data.title
                                        });

                                        //Attach click event to the marker.
                                        (function (marker, data) {
                                            google.maps.event.addListener(marker, "click", function (e) {
                                                //Wrap the content inside an HTML DIV in order to set height and width of InfoWindow.
                                                infoWindow.setContent("<div style = 'width:250px;min-height:40px'>" + data.description + "</div>");
                                                infoWindow.open(map, marker);
                                            });
                                        })(marker, data);
                                    }
                                }
                            </script>
                            <div id="dvMap" style="width: 100%;height: 80vh; position: absolute;"></div>

                            <!-- <li>
                            <a data-toggle="tab" data-target="#pages" href="#" class="btn btn-mat">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z" /></svg> <?php echo $wo['lang']['pages'];?>
                            </a>
                        </li> -->
                        <?php } ?>
                    </div>
            </div>
            </center>
        </div>
    </div>

</div>

<script>
   // $('.wow_main_blogs_bg').css('height', ($('.wow_main_float_head').height()) + 'px');

    $(document).on('click', '.wow_srch_drp_mnu', function (e) {
        e.stopPropagation();
    });

    jQuery(document).ready(function($) {
        //Load more users
        $(".load-more-users").click(function(event) {
            var form = document.getElementById('search_form');
            var formdata = new FormData(form);
            var u_offset = ($("[data-search-type=user]").length > 0) ? $("[data-search-type=user]").last().attr('data-id') : 0;
            $.ajax({
                processData: false,
                url: Wo_Ajax_Requests_File()+'?f=load-more-users&offset='+u_offset,
                type: 'POST',
                dataType: 'json',
                data: formdata,
                contentType: false,
                success:function(data){
                    if (data['status'] == 200) {
                        $("#users-cont").append(data['html'])
                    }else{$(".load-more-users").remove()}
                }
            })
        });
        //Load more groups
        $(".load-more-groups").click(function(event) {
            var g_offset = ($("[data-search-type=group]").length > 0) ? $("[data-search-type=group]").last().attr('data-id') : 0;
            $.ajax({
                url: Wo_Ajax_Requests_File(),
                type: 'GET',
                dataType: 'json',
                data: {f: 'load-more-groups',offset:g_offset,query:$("#query").val()},
                success:function(data){
                    if (data['status'] == 200) {
                        $("#groups-cont").append(data['html'])
                    }else{$(".load-more-groups").remove()}
                }
            })
        });
        //Load more pages
        $(".load-more-pages").click(function(event) {
            var p_offset = ($("[data-search-type=page]").length > 0) ? $("[data-search-type=page]").last().attr('data-id') : 0;
            $.ajax({
                url: Wo_Ajax_Requests_File(),
                type: 'GET',
                dataType: 'json',
                data: {f: 'load-more-pages',offset:p_offset,query:$("#query").val()},
                success:function(data){
                    if (data['status'] == 200) {
                        $("#pages-cont").append(data['html'])
                    }else{$(".load-more-pages").remove()}
                }
            })
        });


        $("#input").hover(function(event) {
            $("#input").focus()
        });

    });

    <?php
    $js_array = json_encode($wo['page_sub_categories']);
    echo "var sub_categories_array = ". $js_array . ";\n";
    ?>
    function GetPageSubCategory(self) {
        id = $(self).val();
        var text = "";
        if (typeof(sub_categories_array[id]) == 'undefined') {
            $('#page_sub_category').html('');
        }
        else{
            sub_categories_array[id].forEach(function(entry) {
                text = text + "<option value='"+entry.id+"'>"+entry.lang+"</option>";
            });
            $('#page_sub_category').html(text);
        }
    }


</script>