<?php

if (strlen($wo['page_message']['message']['text']) > 100) {
   $wo['page_message']['message']['text'] = mb_substr( $wo['page_message']['message']['text'], 0, 97, "utf-8") . '...';
}
$unread_class = '';
if (!empty($wo['page_message']['message']) && isset($wo['page_message']['message']['time']) && isset($wo['page_message']['message']['from_id']) && $wo['page_message']['message']['from_id'] != $wo['user']['id']) {
   if ($wo['page_message']['message']['time'] > $wo['user']['lastseen']) {
       $unread_class = ' unread';
   }
}


$page_info = Wo_PageData($wo['page_message']['message']['page_id']);


if ($page_info['user_id'] == $wo['page_message']['message']['from_id']) {
   $message_event = "Wo_OpenChatTab(0,0,0,".$wo['page_message']['message']['page_id'].",".$wo['page_message']['message']['to_id'].");";
}
else{
   $message_event = "Wo_OpenChatTab(0,0,0,".$wo['page_message']['message']['page_id'].",".$wo['page_message']['message']['from_id'].");";
}

$avatar = $page_info['avatar'];
$name = $page_info['page_name'];
if ($page_info['is_page_onwer'] == 1) {
   if ($page_info['user_id'] != $wo['page_message']['message']['from_id']) {
      $user_info = Wo_UserData($wo['page_message']['message']['from_id']);
   }
   else{
      $user_info = Wo_UserData($wo['page_message']['message']['to_id']);
   }
   
   $avatar = $user_info['avatar'];
   $name = $user_info['name'].' ('.$page_info['page_name'].')';
}
$wo['page_message']['message']['text'] = Wo_Emo($wo['page_message']['message']['text']);
?>
<li>
   <div class="notification-list messages-list <?php echo $unread_class;?>" onclick="<?php echo $message_event ?>">
         <div class="notification-user-avatar <?php echo Wo_RightToLeft('pull-left');?>">
            <img src="<?php echo $avatar;?>" alt="<?php echo $name; ?>P">
         </div>
         <div class="clear"></div>
   </div>
</li>