             <?php
                global $sqlConnect;
                global $site_url;
                $intrest_id = $_GET['interest_id'];
                $inerest_data_response = get_data_by_id($sqlConnect, "wo_interest", $intrest_id);
                $interest_date = $inerest_data_response['get_info'];
                $status = $interest_date['status'];
                $image = $interest_date['image'];
                if (isset($_POST['submit'])) {
                    $title = Wo_Secure($_POST['title']);
                    $status = Wo_Secure($_POST['status']);
                    if (empty($title)) {
                        $error = 'Name is required. ';
                    }
                    if (!empty($_FILES['image']['name'])) {
                        //Making directory if not exist
                        $expanse_file_upload_directory    = 'upload/photos';
                        $expanse_file_dir = '';
                        if (!is_dir($expanse_file_dir . $expanse_file_upload_directory)) {
                            mkdir($expanse_file_dir . $expanse_file_upload_directory, 0777, true);
                        }
                        $task_file_replace =  str_replace(" ", "_", $_FILES['image']["name"]);
                        $task_file_name = "upload/photos/" . date('YmdHis_') . "--" . $task_file_replace;
                        //Moving file to the folder
                        $test = move_uploaded_file($_FILES['image']['tmp_name'], $expanse_file_dir . $task_file_name);
                    } else {
                        $task_file_name = $image;
                    }

                    // =======>insert Interest <=====
                    $edit_interest = "UPDATE `wo_interest` SET `name`='$title',`image`='$task_file_name',`status`='$status' WHERE id=$intrest_id";
                    $add_interest_result = mysqli_query($sqlConnect, $edit_interest);
                    if ($add_interest_result) {
                        header("Location: interest");
                    }
                }

                ?>
             <div class="container-fluid">
                 <h3>Knkt Interest</h3>
                 <nav aria-label="breadcrumb">
                     <ol class="breadcrumb">
                         <li class="breadcrumb-item">
                             <a href="#">Home</a>
                         </li>
                         <li class="breadcrumb-item " aria-current="page">Knkt Interest</li>
                         <li class="breadcrumb-item active" aria-current="page">Edit Interest</li>
                     </ol>
                 </nav>

             </div>
             <!-- Form  for data -->
             <form id="contact" action="" method="POST" class="section contact" enctype="multipart/form-data">
                 <div class="row">

                     <div class="col-md-6">
                         <div class="form-group">
                             <label for="usrname"><span class="glyphicon glyphicon-user"></span> Name</label>
                             <input type="text" class="form-control" id="name" name="title" placeholder="Name" value="<?= $interest_date['name'] ?>" required />
                         </div>

                     </div>
                     <div class="col-md-6">
                         <div class="form-group">
                             <label for="image">Image </label>
                             <a href="<?= $site_url . "/" . $interest_date['image']  ?>" target="_blank"><img style="width: 30px;" src="<?= $site_url . '/' . $interest_date['image']; ?>" /></a>
                             <input type="file" class="form-control mb-4" id="image" placeholder="image" value="" name="image" accept="image/*">
                         </div>
                     </div>
                     <div class="col-md-6">
                         <div class="form-group">
                             <label for="status">Status</label>
                             <select name="status" class="form-control mb-4">
                                 <option value="1" <?php echo ($status == 1) ? 'selected' : ''; ?>>Active</option>
                                 <option value="0" <?php echo ($status == 0) ? 'selected' : ''; ?>>Inative</option>
                             </select>
                         </div>
                     </div>

                     <div class="col-md-6">
                         <button type="submit" name="submit" class="col-md-12 btn btn-info mt-4">
                             <span class="glyphicon glyphicon-off"></span> Save
                         </button>
                     </div>
                 </div>
             </form>