<?php if ($wo['loggedin'] == true && Wo_IsMobile() == false) { ?>
	<div class="left-sidebar">
		<ul>
			<li>
				<a href="<?php echo $wo['user']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['user']['username']; ?>">
					<img alt="<?php echo $wo['user']['name'] ?> Profile Picture" src="<?php echo $wo['user']['avatar'] ?>"> <?php echo $wo['user']['name'] ?>
				</a>
			</li>
			<li <?php if ($wo['page'] == 'home') { ?>class="active" <?php } ?>>
				<?php if ($wo['page'] == 'home') { ?>
					<?php if ($wo['config']['order_posts_by'] == 0) { ?>
						<div class="dropdown order_by">
							<svg class="dropdown-toggle" data-toggle="dropdown" role="button" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
								<path fill="currentColor" d="M7,10L12,15L17,10H7Z" />
							</svg>
							<ul class="dropdown-menu dropdown-menu-right" role="button">
								<li class="order_all <?php echo ($wo['user']['order_posts_by'] == 0) ? 'active' : ''; ?>"><a href="javascript:void(0);" onclick="Wo_StorePosts(0);"><?php echo $wo['lang']['all'] ?></a></li>
								<li class="order_people <?php echo ($wo['user']['order_posts_by'] == 1) ? 'active' : ''; ?>"><a href="javascript:void(0);" onclick="Wo_StorePosts(1);"><?php echo $wo['lang']['people_i_follow'] ?></a></li>
							</ul>
						</div>
					<?php } ?>
				<?php } ?>
				<a href="<?php echo $wo['config']['site_url']; ?>" data-ajax="?index.php?link1=home">
					<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> <?php echo $wo['lang']['news_feed']; ?>
				</a>
			</li>
			<?php if ($wo['config']['website_mode'] != 'askfm') { ?>
				<li <?php if ($wo['page'] == 'my_albums') { ?>class="albumactive" <?php } ?>>
					<a href="<?php echo Wo_SeoLink('index.php?link1=albums'); ?>" data-ajax="?link1=albums">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> <?php echo $wo['lang']['albums']; ?>
					</a>
				</li>
			<?php } ?>
			<li <?php if ($wo['page'] == 'saved_posts') { ?>class="savedactive" <?php } ?>>
				<a href="<?php echo Wo_SeoLink('index.php?link1=saved-posts'); ?>" data-ajax="?link1=saved-posts">
					<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> <?php echo $wo['lang']['saved_posts']; ?>
				</a>
			</li>
			<?php if ($wo['config']['events'] == 1 || $wo['config']['forum'] == 1 || $wo['config']['groups'] == 1 || $wo['config']['pages'] == 1 || $wo['config']['poke_system'] == 1) { ?>
				<li class="link_separator"><?php echo $wo['lang']['community']; ?></li>
			<?php } ?>

			<?php if ($wo['config']['events'] == 1) { ?>
				<li <?php if ($wo['page'] == 'events') { ?>class="eventactive" <?php } ?>>
					<a href="<?php echo Wo_SeoLink('index.php?link1=events'); ?>" data-ajax="?link1=events">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> <?php echo $wo['lang']['events'] ?>
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['forum'] == 1) { ?>
				<li>
					<a href="<?php echo Wo_SeoLink('index.php?link1=forum'); ?>" data-ajax="?link1=forum">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> <?php echo $wo['lang']['forum']; ?>
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['groups'] == 1) { ?>
				<li <?php if ($wo['page'] == 'my_groups') { ?>class="groupactive" <?php } ?>>
					<a href="<?php echo Wo_SeoLink('index.php?link1=groups'); ?>" data-ajax="?link1=groups">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> <?php echo $wo['lang']['my_groups']; ?>
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['pages'] == 1) { ?>
				<li <?php if ($wo['page'] == 'my_pages') { ?>class="pageactive" <?php } ?>>
					<a href="<?php echo Wo_SeoLink('index.php?link1=pages'); ?>" data-ajax="?link1=pages">

						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> <?php echo $wo['lang']['my_pages']; ?>
					</a>
				</li>
				<li>
					<a href="https://pfntek.com/loc">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="<?php echo $wo['lang']['welcome_'] ?>" /> My Maps
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['poke_system'] == 1) { ?>
				<li <?php if ($wo['page'] == 'poke') { ?>class="pokeactive" <?php } ?>>
					<a href="<?php echo Wo_SeoLink('index.php?link1=poke'); ?>" data-ajax="?link1=poke">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 30 30">
							<path fill="#009688" d="M1 20.5zM23 12c-.8 0-1.5.5-1.8 1.2L21 13c0-1.1-.9-2-2-2s-2 .9-2 2v-1c0-1.1-.9-2-2-2s-2 .9-2 2V4c0-1.1-.9-2-2-2s-2 .9-2 2v15.5C6.4 18.2 5.3 18 4 18c-1.5 0-3 .6-3 2.5l4.5 2 3.2 3.2c1.5 1.5 3.5 2.3 5.7 2.3H21c2.2 0 4-1.8 4-4V14c0-1.1-.9-2-2-2z" />
						</svg> <span><?php echo $wo['lang']['pokes']; ?></span>
					</a>
				</li>
			<?php } ?>


			<?php if ($wo['config']['blogs'] == 1) { ?>
				<li class="link_separator"><?php echo $wo['lang']['blog']; ?></li>
				<li>
					<a href="<?php echo Wo_SeoLink('index.php?link1=blogs'); ?>" data-ajax="?link1=blogs">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
							<path fill="#f35d4d" d="M19,21 L5,21 C3.34314575,21 2,19.6568542 2,18 L2,3 L16,3 L18,3 L18,8 L22,8 L22,9 L22,18 C22,19.6568542 20.6568542,21 19,21 Z M16.1707057,19 C16.0601542,18.6872211 16,18.3506354 16,18 L16,5 L4,5 L4,18 C4,18.5522847 4.44771525,19 5,19 L16.1707057,19 Z M18,10 L18,18 C18,18.5522847 18.4477153,19 19,19 C19.5522847,19 20,18.5522847 20,18 L20,10 L18,10 Z M10,7 L10,11 L6,11 L6,7 L10,7 Z M14,8 L14,10 L11,10 L11,8 L14,8 Z M14,12 L14,14 L6,14 L6,12 L14,12 Z M14,15 L14,17 L6,17 L6,15 L14,15 Z" />
						</svg> <?php echo $wo['lang']['blog'] ?>
					</a>
				</li>
			<?php } ?>
			<?php if (Wo_CanBlog() == true) { ?>
				<li <?php if ($wo['page'] == 'My-Blogs') { ?>class="blogactive" <?php } ?>>
					<a href="<?php echo Wo_SeoLink('index.php?link1=my-blogs'); ?>" data-ajax="?link1=my-blogs">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
							<path fill="#009da0" d="M15,3.41421356 L15,7 L18.5857864,7 L15,3.41421356 Z M19,9 L15,9 C13.8954305,9 13,8.1045695 13,7 L13,3 L5,3 L5,21 L19,21 L19,9 Z M5,1 L15.4142136,1 L21,6.58578644 L21,21 C21,22.1045695 20.1045695,23 19,23 L5,23 C3.8954305,23 3,22.1045695 3,21 L3,3 C3,1.8954305 3.8954305,1 5,1 Z M8,17 L8,15 L14,15 L14,17 L8,17 Z M8,13 L8,11 L16,11 L16,13 L8,13 Z" />
						</svg> <?php echo $wo['lang']['my_articles'] ?>
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['classified'] == 1) { ?>
				<li class="link_separator"><?php echo $wo['lang']['market']; ?></li>
				<li>
					<a href="<?php echo Wo_SeoLink('index.php?link1=products'); ?>" data-ajax="?link1=products">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png"><?php echo $wo['lang']['market']; ?>
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['classified'] == 1) { ?>
				<li <?php if ($wo['page'] == 'my_products') { ?>class="productactive" <?php } ?>>
					<a href="<?php echo Wo_SeoLink('index.php?link1=my-products'); ?>" data-ajax="?link1=my-products">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png"> <?php echo $wo['lang']['my_products']; ?>
					</a>
				</li>
			<?php } ?>
			<li class="link_separator">Other Things</li>
			<?php if ($wo['config']['popular_posts'] == 1) { ?>
				<li <?php if ($wo['page'] == 'most_liked') { ?>class="popularactive" <?php } ?>>
					<a href="<?php echo $wo['config']['site_url']; ?>/most_liked" data-ajax="?link1=most_liked">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png"> <?php echo TextForMode('popular_posts'); ?>
					</a>
				</li>
			<?php } ?>

			<?php if ($wo['config']['games'] == 1) { ?>
				<li <?php if ($wo['page'] == 'game') { ?>class="gameactive" <?php } ?>>
					<a href="<?php echo Wo_SeoLink('index.php?link1=new-game'); ?>" data-ajax="?link1=new-game">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 30 30">
							<path fill="#03A9F4" d="M28.9 20.2l-2-10.7c-.2-1.2-1.2-2.1-2.3-2.4 0 0-5.5-1.1-9.6-1.1S5.4 7.1 5.4 7.1c-1.2.2-2.1 1.1-2.3 2.3l-2 10.7c-.1.3-.1.6-.1.9 0 2.2 1.8 4 4 4 1.2 0 2.2-.5 3-1.3L9.5 22h11l1.5 1.7c.7.8 1.8 1.3 3 1.3 2.2 0 4-1.8 4-4 0-.3 0-.6-.1-.8zM10 16H9v1c0 .6-.4 1-1 1s-1-.4-1-1v-1H6c-.6 0-1-.4-1-1s.4-1 1-1h1v-1c0-.6.4-1 1-1s1 .4 1 1v1h1c.6 0 1 .4 1 1s-.4 1-1 1zm11 1c0-.6.4-1 1-1s1 .4 1 1-.4 1-1 1-1-.4-1-1zm3-3c.6 0 1 .4 1 1s-.4 1-1 1-1-.4-1-1 .4-1 1-1zm-2-2c.6 0 1 .4 1 1s-.4 1-1 1-1-.4-1-1 .4-1 1-1zm-2 4c-.6 0-1-.4-1-1s.4-1 1-1 1 .4 1 1-.4 1-1 1z" />
						</svg> <?php echo $wo['lang']['games']; ?>
					</a>
				</li>
			<?php } ?>
			<li>
				<a href="<?php echo Wo_SeoLink('index.php?link1=search?query='); ?>" data-ajax="?link1=search">
					<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="<?php echo $wo['lang']['welcome_'] ?>" /> <?php echo $wo['lang']['explore']; ?>
				</a>
			</li>
			<?php if ($wo['config']['memories_system'] == 1) { ?>
				<li <?php if ($wo['page'] == 'memories') { ?>class="memoryactive" <?php } ?>>
					<a href="<?php echo Wo_SeoLink('index.php?link1=memories'); ?>" data-ajax="?link1=memories">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> <?php echo $wo['lang']['memories']; ?>
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['find_friends'] == 1) { ?>
				<li <?php if ($wo['page'] == 'friends_nearby') { ?>class="friendactive" <?php } ?>>
					<a href="<?php echo Wo_SeoLink('index.php?link1=friends-nearby'); ?>" data-ajax="?link1=friends-nearby">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> <?php echo $wo['lang']['find_friends']; ?>
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['movies'] == 1) { ?>
				<li>
					<a href="<?php echo Wo_SeoLink('index.php?link1=movies'); ?>" data-ajax="?link1=movies">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
							<path fill="#8d73cc" d="M23,19 C23,20.1045695 22.1045695,21 21,21 L9,21 C7.8954305,21 7,20.1045695 7,19 L7,5 C7,3.8954305 7.8954305,3 9,3 L21,3 C22.1045695,3 23,3.8954305 23,5 L23,19 Z M6,20 C4.8954305,20 4,19.1045695 4,18 L4,6 C4,4.8954305 4.8954305,4 6,4 L6,20 Z M3,19 C1.8954305,19 1,18.1045695 1,17 L1,7 C1,5.8954305 1.8954305,5 3,5 L3,19 Z M21,19 L21,5 L9,5 L9,19 L21,19 Z M13,9 L17,12 L13,15 L13,9 Z" />
						</svg> <?php echo $wo['lang']['movies']; ?>
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['offer_system'] == 1) { ?>
				<li <?php if ($wo['page'] == 'offers') { ?>class="eventactive" <?php } ?>>
					<a href="<?php echo Wo_SeoLink('index.php?link1=offers'); ?>" data-ajax="?link1=offers">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
							<path fill="#f25e4e" d="M5.5,7A1.5,1.5 0 0,1 4,5.5A1.5,1.5 0 0,1 5.5,4A1.5,1.5 0 0,1 7,5.5A1.5,1.5 0 0,1 5.5,7M21.41,11.58L12.41,2.58C12.05,2.22 11.55,2 11,2H4C2.89,2 2,2.89 2,4V11C2,11.55 2.22,12.05 2.59,12.41L11.58,21.41C11.95,21.77 12.45,22 13,22C13.55,22 14.05,21.77 14.41,21.41L21.41,14.41C21.78,14.05 22,13.55 22,13C22,12.44 21.77,11.94 21.41,11.58Z"></path>
						</svg> <?php echo $wo['lang']['offers']; ?>
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['job_system'] == 1) { ?>
				<li>
					<a href="<?php echo Wo_SeoLink('index.php?link1=jobs'); ?>" data-ajax="?link1=jobs">
						<span title="<?php echo ($wo['lang']['open_to_work']); ?>">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color:#4caf50;">
								<rect x="2" y="7" width="20" height="14" rx="2" ry="2"></rect>
								<path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"></path>
							</svg>
						</span> <?php echo $wo['lang']['jobs']; ?>
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['common_things'] == 1) { ?>
				<li>
					<a href="<?php echo Wo_SeoLink('index.php?link1=common_things'); ?>" data-ajax="?link1=common_things">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> <?php echo $wo['lang']['common_things']; ?>
					</a>
				</li>
				<li>
					<a href="<?php echo Wo_Link('index.php?link1=feedback'); ?>">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> Feedback
					</a>
				</li>
				<li>
					<a href="<?php echo Wo_Link('index.php?link1=chat-rooms&chat_list=0'); ?>">
						<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> Chat Rooms
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['funding_system'] == 1) { ?>
				<li>
					<a href="<?php echo Wo_SeoLink('index.php?link1=funding'); ?>" data-ajax="?link1=funding">
					<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" />
					<line x1="12" y1="1" x2="12" y2="23"></line>
							<path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path>
						</svg> <?php echo $wo['lang']['funding']; ?>
					</a>
				</li>
			<?php } ?>
			<?php if ($wo['config']['website_mode'] == 'linkedin') { ?>
				<li>
					<a href="<?php echo Wo_SeoLink('index.php?link1=open_to_work_posts'); ?>" data-ajax="?link1=open_to_work_posts">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color: #673AB7;">
							<line x1="12" y1="1" x2="12" y2="23"></line>
							<path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path>
						</svg> <?php echo $wo['lang']['open_to_work_posts']; ?>
					</a>
				</li>
			<?php } ?>
			<li>
				<a href="https://pfntek.com/explore">
					<img src="<?php echo $wo['config']['theme_url']; ?>/img/ic.png" alt="" /> Find Friends on Map
				</a>
			</li>
		</ul>
	</div>
<?php } ?>

<script>
	$(document).ready(function() {
		$('div.leftcol').theiaStickySidebar({
			additionalMarginTop: 65
		});
	});

	<?php if ($wo['config']['order_posts_by'] == 0) { ?>

		function Wo_StorePosts(type) {
			if (type > 1) {
				return false;
			}
			if (type == 0) {
				$('.order_all').addClass('active');
				$('.order_people').removeClass('active');
			} else {
				$('.order_all').removeClass('active');
				$('.order_people').addClass('active');
			}
			$('#posts-laoded').html('<div class="wo_loading_post"><div class="wo_loading_post_child"></div></div>');
			$.get(Wo_Ajax_Requests_File() + '?f=update_order_by', {
				type: type
			}, function(data) {
				if (data.status == 200) {
					loadposts();
				}
			});
		}
	<?php } ?>
</script>