<?php
global $site_url, $wo;
$error = $name =  $short_discription =  $detail_discription = "";
$accestoken = Wo_access_token($wo['user']['id']);
if (isset($_POST['submit'])) {
    $name = $_POST['name'];
    if (isset($_FILES['cover_image'])) {
        $cover_image = new CURLFile($_FILES['cover_image']['tmp_name'], $_FILES['cover_image']['type'], $_FILES['cover_image']['name']);
        $cover_image_name = $_FILES['cover_image']['name'];
    }
    if (isset($_FILES['profile_image'])) {
        $profile_image = new CURLFile($_FILES['profile_image']['tmp_name'], $_FILES['profile_image']['type'], $_FILES['profile_image']['name']);
        $profile_image_name = $_FILES['profile_image']['name'];
    }
    $short_discription = $_POST['short_discription'];
    $detail_discription = $_POST['detail_discription'];
    $group_type = $_POST['group_type'];
    if ($name == "") {
        $error = "Name is Required";
    } elseif (empty($_FILES['cover_image']['name'])) {
        $error = "cover image  is required";
    } elseif (empty($_FILES['profile_image']['name'])) {
        $error = "profile image  is required";
    } elseif ($short_discription == "") {
        $error = "Short Describtion  is required";
    } elseif ($detail_discription == "") {
        $error = "Detail discription  is required";
    } elseif ($group_type == "") {
        $error = "Group type is required";
    }
    if ($error == "") {
        $post_data = array(
            "name" => $name,
            "cover_image" => $cover_image,
            "cover_image_name" => $cover_image_name,
            "profile_image" => $profile_image,
            "profile_image_name" => $profile_image_name,
            "short_discription" => $short_discription,
            "detail_discription" => $detail_discription,
            "group_type" => $group_type,
            "server_key" => $wo['config']['widnows_app_api_key'],
        );
        $api_url = "api/create-groups?access_token=" . $accestoken;
        $response = invokeApi('POST', $api_url, $post_data);
        if ($response['data']['api_status'] == "200") {
            header("Location: " . Wo_Link('index.php?link1=chat-rooms&chat_list=' . $group_type));
        } else {
            $error = "Something went wrong please contact to support";
        }
    }
}
if (isset($_GET['action'])  && $_GET['action'] == 'join') {
    $group_id = $_GET['group_id'];
    $api_url = "api/join_groups?access_token=" . $accestoken;
    $post_data = array(
        "server_key" => $wo['config']['widnows_app_api_key'],
        'group_id' => $group_id
    );
    $response = invokeApi('POST', $api_url, $post_data);
    if ($response['data']['api_status'] == '200') {
        $success = $response['data']['message'];
    } else {
        $error =  $response['data']['message'];
    }
}
if (isset($_GET['action']) && $_GET['action'] == 'delete') {
    $group_id = $_GET['group_id'];
    $api_url = "api/delete-groups?access_token=" . $accestoken;
    $post_data = array(
        "server_key" => $wo['config']['widnows_app_api_key'],
        'id' => $group_id
    );
    $response = invokeApi('POST', $api_url, $post_data);
    if ($response['data']['api_status'] == '200') {
        $success = $response['data']['message'];
    } else {
        $error = "some thing went wrong please contact to suuport ";
    }
}

if (isset($_GET['chat_list']) == 0) {
    $group_type = $_GET['chat_list'];
    $post_data = array(
        "server_key" => $wo['config']['widnows_app_api_key'],
        'group_type' => $group_type
    );
} else {
    $group_type = $_GET['chat_list'];
    $post_data = array(
        "server_key" => $wo['config']['widnows_app_api_key'],
        'group_type' => $group_type
    );
}
$api_url = "api/list-groups?access_token=" . $accestoken;
$response = invokeApi('POST', $api_url, $post_data);
$group_list_result = $response['data']['data'];
?>
<link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">
<div class="container">
    <?php
    if ($error != "") {
    ?>
        <div class="alert text-center alert-danger alert-dismissible " role="alert" style="width:50%; margin-left:23%; margin-right:25%;margin-top: 40px; background: #4D91EA;color: white;">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <?= $error; ?>
        </div>
    <?php } else if ($success != "") {
    ?>
        <div class="alert text-center alert-danger alert-dismissible " role="alert" style="width:50%; margin-left:23%; margin-right:25%;margin-top: 40px; background: #4D91EA;color: white;">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <?= $success; ?>
        </div>
    <?php } ?>
    <div class="main sticky-main lg-view-screen" id="main-inner-id">
        <a class="blue-arrow" href="">
            <i class="ri-arrow-left-line"></i>
        </a>

        <div class="public-group " type="" name="" id="add">
            <div class="public-group-img"><i class="ri-add-circle-fill"></i> </div>
            <div class="public-group-para">
                <p>Create New Chat Group</p>
            </div>
        </div>


        <a href="<?php echo $site_url . '/index.php?link1=chat-rooms&chat_list=0' ?>">
            <div class="public-group" type="" name="">
                <div class="public-group-img"><i class="ri-user-3-fill"></i></div>
                <div class="public-group-para">
                    <p>Browse Public Chats Groups</p>
                </div>
            </div>
        </a>

        <a href="<?php echo $site_url . '/index.php?link1=chat-rooms&chat_list=1' ?>">
            <div class="public-group" type="" name="">

                <div class="public-group-img"><i class="ri-lock-fill"></i></div>
                <div class="public-group-para">
                    <p>Browse Private Chat Groups</p>
                </div>
            </div>
        </a>
    </div>
    <!-- mobile view -->
    <div class="main sticky-main mobile_view_screen" id="main-inner-id">
        <a class="blue-arrow" href="">
            <i class="ri-arrow-left-line"></i>
        </a>

        <div class="public-group " type="" name="" id="add">
            <div class="public-group-img"><i class="ri-add-circle-fill"></i> </div>
            <div class="public-group-para">
                <p>Create Group</p>
            </div>
        </div>


        <a href="<?php echo $site_url . '/index.php?link1=chat-rooms&chat_list=0' ?>">
            <div class="public-group" type="" name="">
                <div class="public-group-img"><i class="ri-user-3-fill"></i></div>
                <div class="public-group-para">
                    <p> Public Group</p>
                </div>
            </div>
        </a>

        <a href="<?php echo $site_url . '/index.php?link1=chat-rooms&chat_list=1' ?>">
            <div class="public-group" type="" name="">

                <div class="public-group-img"><i class="ri-lock-fill"></i></div>
                <div class="public-group-para">
                    <p> Private Group</p>
                </div>
            </div>
        </a>
    </div>

</div>
<br><br>
<div class="container" style="width: 95%;">
    <div class="main-body">
        <div class="row gutters-sm">

            <?php if ($group_list_result) {
                foreach ($group_list_result as $group) {
            ?>
                    <div class="col-lg-3 mb-3  col-sm-6 ">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex flex-column ">
                                    <div class="img-in-cover"> <img src="<?php echo $site_url . '/' . $group['cover_image'] ?>" alt="Admin"></div>
                                    <div class="mt-3">
                                        <div>
                                            <p class="text-secondary mb-1 fr-room "><?= $group['name'] ?>
                                            </p>
                                        </div>
                                        <div class="img-in-profile"> <img src="<?= $site_url . '/' . $group['profile_image'] ?>" width="60" id="avatar"></div>
                                        <p class="text-secondary mb-1 group-name"><?= $group['short_discription'] ?></p>
                                        <p class="text-muted font-size-sm" style="word-break: break-word;min-height:120px;"><?= $group['detail_discription'] ?>
                                        </p>
                                        <div class="section chat_see_group">
                                            <?php if ($group['user_data']['0']['user_id'] == $wo['user']['user_id']) { ?>
                                                <div> <a href="<?php echo Wo_Link('index.php?link1=group-chat&group_id=' . $group['id']) ?>"><button class="chat-btn">See Chat</button></a></div>
                                            <?php } else { ?>
                                                <div> <a href="<?php echo Wo_Link('index.php?link1=chat-rooms&chat_list=0&action=join&group_id=' . $group['id']) ?>"><button class="chat-btn">Join Group</button></a></div>
                                            <?php } ?>
                                            &nbsp;
                                            <div><span class="dropdown  icon-post" id="icon-group">
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots" viewBox="0 0 16 16">
                                                            <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z" />
                                                        </svg>
                                                    </a>
                                                    <ul class="dropdown-menu post-privacy-menu post-options" role="menu">
                                                        <li>
                                                            <a href="<?php echo Wo_Link('index.php?link1=edit_groups&group_id=' . $group['id']); ?>"><button>Edit Group</button></a>
                                                        </li>
                                                        <li>
                                                            <a href="<?php echo Wo_Link('index.php?link1=chat-rooms&group_id=' . $group['id'] . '&action=delete'); ?>"> <button>Delete Group</button></a>
                                                        </li>
                                                    </ul>
                                                </span></div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            <?php }
            } ?>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" background-color="white">
    <div class="modal-dialog">
        <div class="modal-content">
            <div style="padding-top:10px;">
                <h3 class="text-center drk_required_style">Create Chat Room</h3>
            </div>
            <form id="contact" action="" method="POST" class="section contact" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="choose-file">
                        <div class="uploading">
                            <button type="button" class="btn-file">
                                <div id="cover-photo">
                                    <i class="ri-image-line"></i>
                                    <span>Cover Photo</span>
                                </div>
                                <input type="file" accept="image/*" name="cover_image" onchange="readURL(this);" accept="">
                                <img class="add-img-media" id="blah" src="" />
                            </button>

                        </div>
                    </div>
                    <div id="btn-img">
                        <button type="button" class="btn-file">
                            <div id="image-icon">
                                <i class="ri-image-line"></i>
                                <span>Profile Photo</span>
                            </div>
                            <input type="file" accept="image/*" name="profile_image" accept="" onchange="readURL2(this);">
                            <img class="add-img-media" id="blah2" src="" />
                        </button>
                    </div>

                    <div class="reqiured-tit ">
                        <div class="row">
                            <div class="col-md-6 drk_required_style">
                                <label style=" padding: 0px; margin: 9px 0px 8px 5px;" for="Add Post Title">Name</label>
                                <input type="text" class="form-control" style="background-color: #f9f9f9;height: 45px;"  id="Post Title" name="name" placeholder="Name" value="<?php echo $name ?>" required />
                            </div>
                            <div class="col-md-6 drk_required_style">
                                <label style=" padding: 0px; margin: 9px 0px 8px 5px;" for="Add Post Title">Short Describtion</label>
                                <input type="text" class="form-control" style="background-color: #f9f9f9;height: 45px;" id="Post Title" name="short_discription" placeholder="Short Describtion" value="<?php $short_discription ?>" required />
                            </div>
                            <div class="col-md-6 drk_required_style">
                                <label style=" padding: 0px; margin: 9px 0px 8px 5px;" for="Add Post Title">Group Privacy</label>
                                <select style="background-color: #f9f9f9;height: 45px;" class="form-control" name="group_type" id="">
                                    <option value="1">Private</option>
                                    <option value="0">Public</option>
                                </select>
                            </div>
                        </div>
                        <div class="row drk_required_style">
                            <label for="Add Post Title">Detail Describtion </label>
                            <div class="container" style="width:100%">
                                <textarea class="form-control" style="background-color: #f9f9f9;height: 95px;margin-bottom:20px;" name="detail_discription" placeholder="Detail Describtion" class="mb-lg-8" value="<?php $detail_discription ?>"></textarea>
                            </div>
                        </div>
                        <button class="btn-post" name="submit" type="submit">Create Group</button>
                    </div>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {

        // Attach Button click event listener 
        $("#add").click(function() {
            // show Modal
            $('#myModal').modal('show');

        });
    });

    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#blah')
                    .attr('src', e.target.result)
                    .width(570)
                    .height(200);

                $('#cover-photo').css('display', 'none');
                $('.uploading').css('padding', '0px');
                $('.choose-file').css('padding', '0px');

                $('.btn-file').css('padding', '0px');
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    function readURL2(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#blah2')
                    .attr('src', e.target.result)
                    .width(60)
                    .height(50);

                $('#image-icon').css('display', 'none');
                $('#image-icon').css('padding', '0px');
                $('#btn-img').css('padding', '0px');
                $('.btn-file').css('padding', '0px');

            };

            reader.readAsDataURL(input.files[0]);
        }


    }
    $(window).scroll(function() {

        if (window.scrollY > 10) {
            $('#main-inner-id').addClass('main-inner-fixed-at')
        } else {
            $('#main-inner-id').removeClass('main-inner-fixed-at')
        }
    })
</script>