<?php
global $site_url, $wo;
$interest_id = $_GET['interest_id'];
$accestoken = Wo_access_token($wo['user']['id']);
// post Like 
$type = $_POST['type'];
if ($type == "1") {
    $post_id = $_POST['post_id'];
    $comment = $_POST['comment'];
    $api_url = "api/create-knkt-post-comment?access_token=" . $accestoken;
    $post_data = array(
        "server_key" => $wo['config']['widnows_app_api_key'],
        'post_id' => $post_id,
        'comment' => $comment
    );
    $post_list_data = invokeApi_test('POST', $api_url, $post_data);
    echo json_encode($post_list_data);
    die;
} else if ($type == "0") {
    $comment_id = $_POST['comment_id'];
    $api_url = "api/delete-knkt-post-comment?access_token=" . $accestoken;
    $post_data = array(
        "server_key" => $wo['config']['widnows_app_api_key'],
        'comment_id' => $comment_id
    );
    $post_list_data = invokeApi('POST', $api_url, $post_data);
    echo json_encode($post_list_data);
    die;
} else if ($type == "2") {
    $comment_id = $_POST['comment_id'];
    $comment = $_POST['comment'];
    $api_url = "api/edit-knkt-post-comment?access_token=" . $accestoken;
    $post_data = array(
        "server_key" => $wo['config']['widnows_app_api_key'],
        'comment_id' => $comment_id,
        'comment' => $comment
    );
    $post_list_data = invokeApi('POST', $api_url, $post_data);
    echo json_encode($post_list_data);
    die;
}
