<?php
global $site_url, $wo;
$accestoken = Wo_access_token($wo['user']['id']);


// user interest list 
if (isset($_GET['alphabet'])) {
    $get_alphabet = $_GET['alphabet'];
    $post_data = array(
        "server_key" => $wo['config']['widnows_app_api_key'],
        "search" => $get_alphabet
    );
} else {
    $post_data = array(
        "server_key" => $wo['config']['widnows_app_api_key']
    );
}
$api_url = "api/list-user-interest?access_token=" . $accestoken;
$interest_show_data_response = invokeApi('POST', $api_url, $post_data);
$user_interest_list = $interest_show_data_response['data']['data']['all_interest'];
// user exist 
$api_url = "api/user-interest-detail?access_token=" . $accestoken;
$post_data = array(
    "server_key" => $wo['config']['widnows_app_api_key'],
    "user_id" => $wo['user']['user_id']
);
$user_interst_result = invokeApi('POST', $api_url, $post_data);
$user_interest = $user_interst_result['data']['data'];
if (isset($_POST['submit'])) {
    $ids = $_POST['interest_id'];
    if (empty($_POST['interest_id'])) {
        $error = "Select One Catagory Aleast";
    }
    if (empty($error)) {
        $ids = implode(',', $ids);
        $post_data = array(
            "server_key" => $wo['config']['widnows_app_api_key'],
            'interest_id' => $ids,
        );
        $api_url = "api/edit-user-interest?access_token=" . $accestoken;
        $response = invokeApi('POST', $api_url, $post_data);
        if ($response['data']['api_status'] == 200) {
            header("Location: " . Wo_Link('index.php?link1=kntn_catagory'));
        }
    }
}
?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/all.min.js" integrity="sha512-naukR7I+Nk6gp7p5TMA4ycgfxaZBJ7MO5iC3Fp6ySQyKFHOGfpkSZkYVWV5R7u7cfAicxanwYQ5D1e17EfJcMA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">
<form id="" action="" method="POST" class="" enctype="multipart/form-data">
    <?php
    if ($error != "") {
    ?>
        <div class="alert text-center alert-danger alert-dismissible " role="alert" style="width:50%; margin-left:23%; margin-right:25%;margin-top: 40px; background: #4D91EA;color: white;">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <?= $error; ?>
        </div>
    <?php } else if ($success != "") {
    ?>
        <div class="alert text-center alert-success alert-dismissible " role="alert" style="width:50%; margin-left:23%; margin-right:25%;">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <?= $success; ?>
        </div>
    <?php } ?>
    <div style="margin: auto; max-width: max-content;">
        <ul class="pagination">
            <?php
            $character = range('A', 'Z');
            ?>
            <li class=" active"><a href="<?php echo $site_url . "/index.php?link1=edit_interest&user_id=" . $wo['user']['user_id'] ?>">X</a></li>
            <?php
            foreach ($character as $alphabet) {
            ?>
                <li <?php if ($alphabet == $get_alphabet) { ?> class=" active" <?php } ?>><a href="<?php echo $site_url . "/index.php?link1=edit_interest&user_id=" . $wo['user']['user_id'] . '&alphabet=' . $alphabet ?>"><?php echo $alphabet ?></a></li>
            <?php } ?>

        </ul>
    </div>


    <div id="setMainDiv">

        <?php
        if ($user_interest_list) {


            foreach ($user_interest_list as $interest_list) { ?>
                <div id="flexbox1">
                    <div class="column1">
                        <input onclick="myFunction()" type="checkbox" class="select-interest" name="interest_id[]" value="<?php echo $interest_list['id'] ?>" id="cb<?php echo $interest_list['id'] ?>" <?php
                                                                                                                                                                                                        foreach ($user_interest as $interest_id) {
                                                                                                                                                                                                            echo ($interest_list['id'] == $interest_id['interest_id'] ? 'checked' : '');
                                                                                                                                                                                                        }
                                                                                                                                                                                                        ?> />
                        <label for="cb<?php echo $interest_list['id'] ?>">
                            <img id="setimg" class="imagess" src="<?php echo $site_url . '/' . $interest_list['image']; ?>" />
                            <div class="centered">
                                <h4><?php echo $interest_list['name'] ?></h4>
                            </div>
                        </label>
                    </div>
                </div>
            <?php } ?>
    </div>
    <div class="btn-submit">
        <button type="submit" name="submit" class="btn-btn1">Submit</button>
    </div>
<?php } ?>
</form>