<?php global $site_url, $wo;
$post_id = $_GET['post_id'];
$interest_id = $_GET['interest_id'];
$page_type = $_GET['page_type'];
$accestoken = Wo_access_token($wo['user']['id']);
$post_data = array(
    "server_key" => $wo['config']['widnows_app_api_key'],
    "post_id" => $post_id
);
// detail api add new post 
$api_url = "api/detail-knkt-post?access_token=" . $accestoken;
$interest_show_data_response = invokeApi('POST', $api_url, $post_data);
$user_interest_list = $interest_show_data_response['data']['data'];
$user_data = $user_interest_list['user_data'];
$interest_list = $user_interest_list['user_post_interest'];
$post_image = $user_interest_list['images'][0]['media'];
$media_type = $user_interest_list['images'][0]['media_type'];
// print_r($media_type);die;
// add user view
$post_data = array(
    "server_key" => $wo['config']['widnows_app_api_key'],
    "post_id" => $post_id,
    "user_id" => $wo['user']['user_id']
);
// detail api add new post 
$api_url = "api/view_post?access_token=" . $accestoken;
invokeApi('POST', $api_url, $post_data);
?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/all.min.js" integrity="sha512-naukR7I+Nk6gp7p5TMA4ycgfxaZBJ7MO5iC3Fp6ySQyKFHOGfpkSZkYVWV5R7u7cfAicxanwYQ5D1e17EfJcMA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">

<!-- sidebar -->
<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<!-- post view -->
<div class="view-post-responsive">
<div class="post-top-outer post-view-main " >  

<a href="index.php?link1=knkt_post&interest_id=<?php echo $interest_id; ?>"><i class="fa fa-arrow-circle-left  " aria-hidden="true" style="margin-right: 97%;padding-top: 7px; font-size: x-large;color: #4D91EA;"></i></a>
          
    <div class="post-top view-post-top ">
   
        <div class="dp-main">
            <div class="dp">
                <img src="<?php echo $site_url.'/'.$user_data['avatar']?>" alt="">
            </div>

            <div class="post-info ">
                <a href="" ><span><?php echo $user_interest_list['post_title'] ?></span></a>

                <a href=""><span class="name"> @<?php echo $user_data['first_name']." ". $user_data['last_name']?></span></a>
                <span class="time view-post-time"><i class="fa fa-location-dot"></i><?php echo $user_interest_list['location'] ?></span>
                   
                

            </div>
        </div>

      <?php 
      
      if($user_data['user_id']==$wo['user']['user_id']) {?>
            <span class="dropdown  icon-post">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down">
                        <polyline points="6 9 12 15 18 9">

                        </polyline>
                    </svg>
                </a>
                <ul class="dropdown-menu post-privacy-menu post-options" role="menu">
                    <li>
                        <button >Edit Post</button>
                    </li>
                    <li>
                        <a href="">Delete Post</a>
                    </li>
                </ul>
            </span>
     <?php }?>
    </div>
    <div class="post-content ">
        <p><?php echo $user_interest_list['post_describtions'] ?></p>
        <!-- <div style="display: flex; margin-top:20px">
           
                <p style="padding-left: 9px; color: blue">
                car
                </p>
           
        </div> -->
     <?php if($media_type=='0') {?>
            <img src="<?php echo $site_url.'/'.$post_image?>" alt="" style="width: 100%;height:auto" >
<?php  }else{
    ?> <audio controls class="audio_post_view">
    <source src="<?php echo $site_url.'/'.$post_image?>"  type="audio/mpeg">
</audio>
    <?php } ?>
    </div>
    <div class="post-bottom">
        <div class="post-bottom-inner">
            <div class="action sweet-candy">
                <input type="hidden" class="lk" name="like" id="<?php echo $post_id ?>" value="1">
                <?php
                if ($user_interest_list['like_data']['user_id'] == $wo['user']['user_id']) {
                    $like = "ri-thumb-up-fill";
                } else {
                    $like = "ri-thumb-up-line";
                }
                ?>
                <i id="like-btn<?php echo $count ?>" class="<?php echo $like ?> thumb">&nbsp;<span>Like</span></i>
            </div>
            <div class="action">
                <i class="ri-chat-2-fill comment" id="<?php echo $count ?>">&nbsp;<span>Comment</span></i>

            </div>
            <form accept="" method="POST" enctype="multipart/form-data">
                <div class="action">
                    <a style="text-decoration: none;" href="<?php echo $site_url . $currentUrl . "&action=share&post_id=" . $user_interest_list['id'] ?>"><i class="ri-share-line">&nbsp;<span>Share</span></i></a>

                </div>

            </form>
            <?php if ($user_interest_list['user_data']['user_id'] != $wo['user']['user_id']) {
                if ($user_interest_list['fellow'] == '1') {
                    $color = "blue";
                } else {
                    $color = "#616770";
                }
            ?>
                <div class="action">
                    <i style="color: <?php echo $color ?>;" class="ri-contacts-line" id="follow">&nbsp;<span style="color: <?php echo $color ?>;">Follow</span></i>
                    <input type="hidden" id="user" value="<?php echo $user_interest_list['user_data']['user_id'] ?>">
                </div>
                <div class="action">
                    <a href="<?php echo $site_url . "/messages" . "/" . $user_interest_list['user_data']['user_id']; ?>" target="_blank"><i class="ri-message-fill">&nbsp;<span>Massage</span></i></a>

                </div>
            <?php
            } ?>
        </div>
    </div>
    <div class="message-box" id="message-text">
        <?php foreach ($user_interest_list['comment_list'] as $comment_list) {
            if ($comment_list) { ?>
                <div class="add-post-comment" id="ak<?php echo $comment_list['id'] ?>">
                    <div class="comment-img"><img src="<?php echo $comment_list['avatar'] ?>" alt=""></div>
                    <div id="add-post">
                        <span>
                            <?php echo $comment_list['first_name'] . " " . $comment_list['last_name'] ?>
                        </span>
                        <span class="sample" id="inner-text<?php echo $comment_list['id'] ?>"><?php echo $comment_list['comment'] ?>
                        </span>
                    </div>
                    <?php if ($comment_list['created_by'] == $wo['user']['user_id']) { ?>
                        <div id="icon-1" data-comment="<?php echo $comment_list['id'] ?>"><i class="ri-delete-bin-line " id="<?php echo $comment_list['id'] ?>"></i></div>
                        <div id="icon-2"><i class="ri-pencil-line" id="<?php echo $comment_list['id'] ?>"></i></div>
                    <?php } ?>
                </div>
                <div class="inner-inp" id="inner-edit-inp<?php echo $comment_list['id'] ?>" style="display: none ;">
                    <div class="inner-img"><img src="<?php echo  $user_image ?>" alt=""></div>
                    <div class="inner-input-field "><input type="text" name="edit" id="edit-cmt<?php echo $comment_list['id'] ?>" value="<?php echo $comment_list['comment'] ?>"></div>
                    <div class="comment-icon">
                        <i id="<?php echo $comment_list['id'] ?>" class="ri-send-plane-2-fill edit" style=""></i>
                    </div>
                </div>
        <?php }
        } ?>
    </div>
    <div class="comment">
        <div style="display: none;" class="comment-section" id="hello<?php echo $count ?>">
            <div class="comment-img">
                <img src="<?php echo $wo['user']['avatar']?>" alt="">
            </div>
            <div class="comment-inp">
                <input type="text" name="message_text" id="message" placeholder="Write a comment and press enter">
                <input type="hidden" name="" id="username" value=<?php echo $wo['user']['first_name']." ". $wo['user']['last_name']?>>
                <input type="hidden" name="" id="user_image" value=<?php echo  $wo['user']['avatar'] ?>>
                <input type="hidden" name="" id="post_id" value=<?php echo  $post_id ?>>
            </div>
            <div class="coment-icon">
                <i id="" class="ri-send-plane-2-fill comment-btn"></i>
            </div>
        </div>
    </div>
</div>
</div>

<script>
    function edit_post(post_id, stit_url) {
        window.location = stit_url + "index.php?link1=edit_post&post_id=" + post_id + "&page_type=edit";
    }
    $('.ri-contacts-line').click(function() {
        let count = $(this).attr("id");
        let follow_id = $('#user').val();
        $.ajax({
            url: "index.php?link1=knkt_follow",
            type: "POST",
            data: {
                following_id: follow_id,

            },
            success: function(data) {
                data = JSON.parse(data);
                let follow_status = data.data.follow_status;
                if (follow_status == 'followed') {
                    $("#" + count).css('color', 'blue');
                    $("#" + count).children().css('color', 'blue');
                } else {
                    $("#" + count).css('color', '#616770');
                    $("#" + count).children().css('color', '#616770');
                }
            }
        })



    })
    $(document).ready(function() {
        $(".comment").click(function() {
            var a = $(this).attr('id');
            $('#hello' + a).toggle();
        });

        $(".comment-btn").click(function() {
            let input_value = $("#message").val();
            let user_name = $("#username").val();
            let user_image = $("#user_image").val();
            let post_id = $("#post_id").val();
            
            $.ajax({
                url: "index.php?link1=create_comment",
                type: "POST",
                data: {
                    post_id: post_id,
                    comment: input_value,
                    type: "1"
                },
                success: function(data) {
                    data = JSON.parse(data);
                    console.log(data.comment_id);
                    let comment_id = data.comment_id;
                    console.log(comment_id);
                    let comment = data.comment;
                    console.log(comment);
                j=$('#message-text').append(
                        `<div class="add-post-comment" id="ak${comment_id}">
                <div class="comment-img"><img src="${user_image}" alt=""></div>
                        <div id="add-post">
                            <span>${user_name}</span>
                            <span"  class="sample" id="inner-text${comment_id}">${input_value}</span>
                        </div>
                        <div id="icon-1" data-comment="${comment_id}"><i class=ri-delete-bin-line id=${comment_id}></i>
                        </div>
                        <div id="icon-2"><i class="ri-pencil-line" id=${comment_id}></i>
                        </div>
                </div>
                <div class="inner-inp" id="inner-edit-inp${comment_id}" style="display: none ;">
                            <div class="inner-img"><img src="${user_image}" alt=""></div>
                            <div class="inner-input-field "><input type="text" name="edit" id="edit-cmt${comment_id}" value="${comment}"></div>
                            <div class="comment-icon">
                                <i id="${comment_id}" class="ri-send-plane-2-fill edit" style=""></i>
                            </div>
                        </div>
                `

                    );
                    console.log(j);
                }
            })
        });
        $(document).on("click", ".edit", function() {
            let comment_id = $(this).attr('id');
            let edit_value = $("#edit-cmt" + comment_id).val()
            $.ajax({
                url: "index.php?link1=create_comment",
                type: "POST",
                data: {
                    comment_id: comment_id,
                    comment: edit_value,
                    type: "2"
                },
                success: function(data) {
                    data = JSON.parse(data);
                    let response = data.data.status
                    if (response == '1') {
                        let comment = data.data.comment
                        $("#inner-edit-inp" + comment_id).css("display", "none");
                        $('#inner-text' + comment_id).text(comment)


                    }

                }
            })
        })
        $(document).on("click", ".ri-pencil-line", function() {
            let comment_id = $(this).attr('id');
            $('#inner-edit-inp' + comment_id).toggle(function() {
                $("#inner-edit-inp").css("display", "flex")
            }, function() {
                $("#inner-edit-inp").css("display", "none")
            });
        })

        $(document).on("click", ".ri-delete-bin-line", function() {
            let comment_id = $(this).attr('id');
            $.ajax({
                url: "index.php?link1=create_comment",
                type: "POST",
                data: {
                    comment_id: comment_id,
                    type: "0"
                },
                success: function(data) {
                    data = JSON.parse(data);
                    let response = data.data.status
                    if (response == '1') {
                        $('#ak' + comment_id).css('display', 'none')
                        $("#inner-edit-inp" + comment_id).css("display", "none");
                    }

                }
            })
        })

        $('.sweet-candy').click(function(e) {
            var post_ids = $(this).find('.lk').attr('id');
            var value = $(this).find('.lk').val();
            var icon = $(this).find('.thumb').attr('id');
            if (value == "1") {
                $(this).find('.lk').val(0);
            } else {
                $(this).find('.lk').val(1);
            }
            $.ajax({
                url: "index.php?link1=like_post",
                type: "POST",
                data: {
                    post_id: post_ids,
                    post_like: value,
                },
                success: function(data) {
                    data = JSON.parse(data);
                    like_status = data.data.like_status
                    if (like_status == 1) {
                        $("#" + icon).addClass('ri-thumb-up-fill');

                        $("#" + icon).removeClass('ri-thumb-up-line');
                    } else {
                        $("#" + icon).removeClass('ri-thumb-up-fill');
                        $("#" + icon).css('color', 'blue');
                        $("#" + icon).addClass('ri-thumb-up-line');
                    }


                }
            })
        });
        $(window).scroll(function() {
            if (window.scrollY > 10) {
                $('#main-inner-id').addClass('main-inner-fixed')
            } else {
                $('#main-inner-id').removeClass('main-inner-fixed')
            }
        })

    });
</script>